apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-go-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grpc-go-helloworld
  template:
    metadata:
      labels:
        run: grpc-go-helloworld
    spec:
      containers:
      - name: grpc-go-helloworld
        image: grpc-go-helloworld
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP 
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-go-helloworld
  namespace: default
spec:
  ports:
    - port: 50051 
      protocol: TCP
      targetPort: 50051
      name: grpc
  selector:
    run: grpc-go-helloworld
  sessionAffinity: None
  clusterIP: None
