apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      run: java-helloworld
  template:
    metadata:
      labels:
        run: java-helloworld
    spec:
      containers:
      - name: java-helloworld
        image: java-helloworld
        resources:
            limits:
              memory: 512M
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: helloport
---
apiVersion: v1
kind: Service
metadata:
  name: java-helloworld
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: helloport
  selector:
    run: java-helloworld
  sessionAffinity: None
  clusterIP: None
