apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-rc
spec:
  replicas: 1
  selector:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello 
        ports:
        - containerPort: 80
